### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by TamberP** [Cyberboss/BYOND.TopicSender#3]
Hello,
I couldn't seem to find a better way to raise this to your notice, but your repo token & NuGet API key are publically available in your appveyor config, and I'm not sure if this was intentional or particularly desired.

Apologies if this is something you already knew about!

**Comment by Cyberboss** [comment]
Thanks for the concern! Luckily those are [AppVeyor encrypted values](https://www.appveyor.com/docs/build-configuration/#secure-variables) so they are safe to display there.
